name: Build LeveHelper

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Dalamud
        if: "!contains(github.event.head_commit.message, '[stg]')"
        run: |
          curl -o latest.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
          unzip latest.zip -d ~/dalamud/

      - name: Download Dalamud staging
        if: "contains(github.event.head_commit.message, '[stg]')"
        run: |
            curl -o latest.zip https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
            unzip latest.zip -d ~/dalamud/

      - name: Build
        run: dotnet build -c Release -p:IsCI=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/*

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: LeveHelper ${{ github.ref_name }}
          files: bin/LeveHelper/latest.zip

      - name: Trigger Repo Update
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: Haselnussbomber/MyDalamudPlugins
          event-type: new-release
